/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author Daniele_38
 */
public class Agenda extends javax.swing.JFrame {

	private final AgendaController controller;

	/**
	 * Creates new form Agenda
	 */
	public Agenda() {
		initComponents();
		controller = new AgendaController(this);
		iniciar();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                banco1 = new Model.DAO.Banco();
                jLabel2 = new javax.swing.JLabel();
                jLabelHoraAgend = new javax.swing.JLabel();
                jLabelClientAgend = new javax.swing.JLabel();
                jLabelObsAgenda = new javax.swing.JLabel();
                jTextFieldValor = new javax.swing.JTextField();
                jTextFieldHora = new javax.swing.JTextField();
                jButtonAgendar = new javax.swing.JButton();
                jLabelvalorAgenda = new javax.swing.JLabel();
                jLabelServAgend1 = new javax.swing.JLabel();
                jScrollPaneAgenda = new javax.swing.JScrollPane();
                jTableAgendamentos = new javax.swing.JTable();
                jTextFieldData = new javax.swing.JTextField();
                jLabelDataAgend1 = new javax.swing.JLabel();
                jLabelIdAgenda2 = new javax.swing.JLabel();
                jScrollPaneObs = new javax.swing.JScrollPane();
                jTextPaneObs = new javax.swing.JTextPane();
                jComboBoxServico = new javax.swing.JComboBox<>();
                jComboBoxCliente = new javax.swing.JComboBox<>();
                jTextFieldId = new javax.swing.JTextField();
                jLabelAgendaFumaca = new javax.swing.JLabel();
                jLabelFundoAgenda = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Agenda");
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Agenda");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 50));

                jLabelHoraAgend.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelHoraAgend.setForeground(new java.awt.Color(0, 0, 0));
                jLabelHoraAgend.setText("Hora");
                getContentPane().add(jLabelHoraAgend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

                jLabelClientAgend.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelClientAgend.setForeground(new java.awt.Color(0, 0, 0));
                jLabelClientAgend.setText("Cliente");
                getContentPane().add(jLabelClientAgend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

                jLabelObsAgenda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelObsAgenda.setForeground(new java.awt.Color(0, 0, 0));
                jLabelObsAgenda.setText("Observação");
                getContentPane().add(jLabelObsAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));
                getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 240, 35));
                getContentPane().add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 240, 35));

                jButtonAgendar.setBackground(new java.awt.Color(0, 102, 255));
                jButtonAgendar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                jButtonAgendar.setForeground(new java.awt.Color(255, 255, 255));
                jButtonAgendar.setText("Agendar");
                jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonAgendarActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 480, 40));

                jLabelvalorAgenda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelvalorAgenda.setForeground(new java.awt.Color(0, 0, 0));
                jLabelvalorAgenda.setText("Valor");
                getContentPane().add(jLabelvalorAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

                jLabelServAgend1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelServAgend1.setForeground(new java.awt.Color(0, 0, 0));
                jLabelServAgend1.setText("Serviço");
                getContentPane().add(jLabelServAgend1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

                jTableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null}
                        },
                        new String [] {
                                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
                        }
                ));
                jScrollPaneAgenda.setViewportView(jTableAgendamentos);

                getContentPane().add(jScrollPaneAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1000, 170));

                jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldDataActionPerformed(evt);
                        }
                });
                getContentPane().add(jTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 240, 35));

                jLabelDataAgend1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelDataAgend1.setForeground(new java.awt.Color(0, 0, 0));
                jLabelDataAgend1.setText("Data");
                getContentPane().add(jLabelDataAgend1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

                jLabelIdAgenda2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelIdAgenda2.setForeground(new java.awt.Color(0, 0, 0));
                jLabelIdAgenda2.setText("Id");
                getContentPane().add(jLabelIdAgenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

                jScrollPaneObs.setViewportView(jTextPaneObs);

                getContentPane().add(jScrollPaneObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 480, 260));

                jComboBoxServico.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                jComboBoxServicoItemStateChanged(evt);
                        }
                });
                jComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBoxServicoActionPerformed(evt);
                        }
                });
                getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 240, 40));

                getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 240, 40));

                jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldIdActionPerformed(evt);
                        }
                });
                getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 240, 35));

                jLabelAgendaFumaca.setForeground(new java.awt.Color(255, 255, 255));
                jLabelAgendaFumaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Imagens/sport-smoke.png"))); // NOI18N
                getContentPane().add(jLabelAgendaFumaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

                jLabelFundoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Imagens/AgendaFundo.png"))); // NOI18N
                getContentPane().add(jLabelFundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -410, 1200, 1000));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldIdActionPerformed

        private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
		this.controller.agendar();
        }//GEN-LAST:event_jButtonAgendarActionPerformed

        private void jComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jComboBoxServicoActionPerformed

        private void jComboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxServicoItemStateChanged
               this.controller.atualizaValor();
        }//GEN-LAST:event_jComboBoxServicoItemStateChanged

        private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldDataActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Agenda().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private Model.DAO.Banco banco1;
        private javax.swing.JButton jButtonAgendar;
        private javax.swing.JComboBox<String> jComboBoxCliente;
        private javax.swing.JComboBox<String> jComboBoxServico;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabelAgendaFumaca;
        private javax.swing.JLabel jLabelClientAgend;
        private javax.swing.JLabel jLabelDataAgend1;
        private javax.swing.JLabel jLabelFundoAgenda;
        private javax.swing.JLabel jLabelHoraAgend;
        private javax.swing.JLabel jLabelIdAgenda2;
        private javax.swing.JLabel jLabelObsAgenda;
        private javax.swing.JLabel jLabelServAgend1;
        private javax.swing.JLabel jLabelvalorAgenda;
        private javax.swing.JScrollPane jScrollPaneAgenda;
        private javax.swing.JScrollPane jScrollPaneObs;
        private javax.swing.JTable jTableAgendamentos;
        private javax.swing.JTextField jTextFieldData;
        private javax.swing.JTextField jTextFieldHora;
        private javax.swing.JTextField jTextFieldId;
        private javax.swing.JTextField jTextFieldValor;
        private javax.swing.JTextPane jTextPaneObs;
        // End of variables declaration//GEN-END:variables

	private void iniciar() {
		this.controller.atualizaTabela();
		this.controller.atualizaCliente();
		this.controller.atualizaServico();
		this.controller.atualizaValor();
	}

	public JComboBox<String> getjComboBoxCliente() {
		return jComboBoxCliente;
	}
		
	public void setjComboBoxCliente(JComboBox<String> jComboBoxCliente) {
		this.jComboBoxCliente = jComboBoxCliente;
	}

	public JComboBox<String> getjComboBoxServico() {
		return jComboBoxServico;
	}

	public void setjComboBoxServico(JComboBox<String> jComboBoxServico) {
		this.jComboBoxServico = jComboBoxServico;
	}

	public JTable getjTableAgendamentos() {
		return jTableAgendamentos;
	}

	public void setjTableAgendamentos(JTable jTableAgendamentos) {
		this.jTableAgendamentos = jTableAgendamentos;
	}

	public JTextField getjTextFieldValor() {
		return jTextFieldValor;
	}

	public void setjTextFieldValor(JTextField jTextFieldValor) {
		this.jTextFieldValor = jTextFieldValor;
	}

	public JTextField getjTextFieldId() {
		return jTextFieldId;
	}

	public void setjTextFieldId(JTextField jTextFieldId) {
		this.jTextFieldId = jTextFieldId;
	}

	public JTextPane getjTextPaneObs() {
		return jTextPaneObs;
	}

	public void setjTextPaneObs(JTextPane jTextPaneObs) {
		this.jTextPaneObs = jTextPaneObs;
	}

	public JTextField getjTextFieldData() {
		return jTextFieldData;
	}

	public void setjTextFieldData(JTextField jTextFieldData) {
		this.jTextFieldData = jTextFieldData;
	}

	public JTextField getjTextFieldHora() {
		return jTextFieldHora;
	}

	public void setjTextFieldHora(JTextField jTextFieldHora) {
		this.jTextFieldHora = jTextFieldHora;
	}
	
	
	
	
		
}
