/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Model.DAO.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Daniele_38
 */
public class Login extends javax.swing.JFrame {

	private final LoginController controller;
	
	/**
	 * Creates new form Login
	 */
	public Login() {
		initComponents();
		controller = new LoginController(this);
		Banco.inicia();
	}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPasswordSenha = new javax.swing.JPasswordField();
                jButtonLogin = new javax.swing.JButton();
                jTextFieldUsuario = new javax.swing.JTextField();
                jLabelUsuario = new javax.swing.JLabel();
                jLabelSenha = new javax.swing.JLabel();
                jLabelLogin = new javax.swing.JLabel();
                jLabelFundo = new javax.swing.JLabel();
                jLabelImagenBarbearia = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Login");
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPasswordSenha.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jPasswordSenhaActionPerformed(evt);
                        }
                });
                getContentPane().add(jPasswordSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 200, 40));

                jButtonLogin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jButtonLogin.setText("Entrar");
                jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonLoginActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 200, 50));
                getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 200, 40));

                jLabelUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
                jLabelUsuario.setText("Usuário");
                getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

                jLabelSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
                jLabelSenha.setText("Senha");
                getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

                jLabelLogin.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
                jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
                jLabelLogin.setText("Login");
                getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

                jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Imagens/painel-login.png"))); // NOI18N
                getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-49, 120, 480, 390));

                jLabelImagenBarbearia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Imagens/Logo_1.jpg"))); // NOI18N
                getContentPane().add(jLabelImagenBarbearia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jPasswordSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordSenhaActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jPasswordSenhaActionPerformed

        private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
                // executa quando clico no botao
		/*this.controller.fizTarefa();
		System.out.println(jTextFieldUsuario.getText());
		System.out.println(jPasswordSenha.getText());*/
		this.controller.entrarNoSistema();
		
        }//GEN-LAST:event_jButtonLoginActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonLogin;
        private javax.swing.JLabel jLabelFundo;
        private javax.swing.JLabel jLabelImagenBarbearia;
        private javax.swing.JLabel jLabelLogin;
        private javax.swing.JLabel jLabelSenha;
        private javax.swing.JLabel jLabelUsuario;
        private javax.swing.JPasswordField jPasswordSenha;
        private javax.swing.JTextField jTextFieldUsuario;
        // End of variables declaration//GEN-END:variables

	public void exibeMensagem(String mensagem) {
		JOptionPane.showMessageDialog(null, mensagem);
	
	}

	public JPasswordField getjPasswordSenha() {
		return jPasswordSenha;
	}

	public void setjPasswordSenha(JPasswordField jPasswordSenha) {
		this.jPasswordSenha = jPasswordSenha;
	}

	public JTextField getjTextFieldUsuario() {
		return jTextFieldUsuario;
	}

	public void setjTextFieldUsuario(JTextField jTextFieldUsuario) {
		this.jTextFieldUsuario = jTextFieldUsuario;
	}
	
	
			
}

	
	

	

