/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuPrincipalController;

/**
 *
 * @author Daniele_38
 */
public class MenuPrincipal extends javax.swing.JFrame {

	private final MenuPrincipalController controller;

	/**
	 * Creates new form MenuPrincipal
	 */
	public MenuPrincipal() {
		initComponents();
		this.controller =  new MenuPrincipalController(this);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabelFundoPrincipal = new javax.swing.JLabel();
                jMenuBarPrincipal = new javax.swing.JMenuBar();
                jMenuCadastro = new javax.swing.JMenu();
                jMenuItemCliente = new javax.swing.JMenuItem();
                jMenuItemServico = new javax.swing.JMenuItem();
                jMenuItemUsuario = new javax.swing.JMenuItem();
                jMenuOperacao = new javax.swing.JMenu();
                jMenuItemAgenda = new javax.swing.JMenuItem();
                jMenuRelatorio = new javax.swing.JMenu();
                jMenuItemTrabalho = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Sistema Barbearia");
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Imagens/fundo-MenuPrincipal.jpg"))); // NOI18N
                getContentPane().add(jLabelFundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                jMenuCadastro.setText("Cadastro");
                jMenuCadastro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

                jMenuItemCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Icon/cliente-icon.png"))); // NOI18N
                jMenuItemCliente.setText("Cliente");
                jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItemClienteActionPerformed(evt);
                        }
                });
                jMenuCadastro.add(jMenuItemCliente);

                jMenuItemServico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jMenuItemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Icon/tesoura-icon.png"))); // NOI18N
                jMenuItemServico.setText("Serviço");
                jMenuItemServico.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItemServicoActionPerformed(evt);
                        }
                });
                jMenuCadastro.add(jMenuItemServico);

                jMenuItemUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Icon/usuario-icon.png"))); // NOI18N
                jMenuItemUsuario.setText("Usuário");
                jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItemUsuarioActionPerformed(evt);
                        }
                });
                jMenuCadastro.add(jMenuItemUsuario);

                jMenuBarPrincipal.add(jMenuCadastro);

                jMenuOperacao.setText("Operação");
                jMenuOperacao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

                jMenuItemAgenda.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jMenuItemAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Icon/agenda-icon.png"))); // NOI18N
                jMenuItemAgenda.setText("Agenda");
                jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItemAgendaActionPerformed(evt);
                        }
                });
                jMenuOperacao.add(jMenuItemAgenda);

                jMenuBarPrincipal.add(jMenuOperacao);

                jMenuRelatorio.setText("Relatório");
                jMenuRelatorio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

                jMenuItemTrabalho.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jMenuItemTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia/View/Icon/relatorioTrabalho-icon.png"))); // NOI18N
                jMenuItemTrabalho.setText("Trabalho");
                jMenuRelatorio.add(jMenuItemTrabalho);

                jMenuBarPrincipal.add(jMenuRelatorio);

                setJMenuBar(jMenuBarPrincipal);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jMenuItemClienteActionPerformed

        private void jMenuItemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jMenuItemServicoActionPerformed

        private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

        private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed
                // TODO add your handling code here:
		this.controller.navegarParaAgenda();
        }//GEN-LAST:event_jMenuItemAgendaActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuPrincipal().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabelFundoPrincipal;
        private javax.swing.JMenuBar jMenuBarPrincipal;
        private javax.swing.JMenu jMenuCadastro;
        private javax.swing.JMenuItem jMenuItemAgenda;
        private javax.swing.JMenuItem jMenuItemCliente;
        private javax.swing.JMenuItem jMenuItemServico;
        private javax.swing.JMenuItem jMenuItemTrabalho;
        private javax.swing.JMenuItem jMenuItemUsuario;
        private javax.swing.JMenu jMenuOperacao;
        private javax.swing.JMenu jMenuRelatorio;
        // End of variables declaration//GEN-END:variables
}
